version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    image: rohith0702/forex:latest
    container_name: backend_app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/postgres
      DATABASE_USER: admin
      DATABASE_PASSWORD: 1234
    ports:
      - "8081:8081"
    networks:
      - app_network

  frontend:
    image: rohith0702/forex-frontend:latest
    container_name: frontend_app
    depends_on:
      - backend
    ports:
      - "82:4173"
    networks:
      - app_network

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge
